### ISSUE TITLE
Use proper means for writing XML in DataFascade

### ISSUE THREAD

**Issue by kuleszdl** [kuleszdl/SIFEI#101]
The data fascade uses 'hand-made' stringbuilders to create XML. This needs refactoring to use some standard Java XML builder, e.g. the DOM builder.

**Comment by krauswg** [comment]
Marked as deprecated (https://github.com/kuleszdl/Spreadsheet-Inspection-Framework/blob/master/src/sif/IO/DataFacade.java#L264), replaced by getFindingsAsJaxb https://github.com/kuleszdl/Spreadsheet-Inspection-Framework/blob/master/src/sif/IO/DataFacade.java#L444.
Or did I miss something?

**Comment by kuleszdl** [comment]
We don't need backwards compatibility yet. Are there any callers which use the deprecated methods? Otherwise I would suggest to simply remove it.
