### ISSUE TITLE
Inspection terminates with Code 259

### ISSUE THREAD

**Issue by kuleszdl** [kuleszdl/SIFEI#94]
I tried running the current SIF/SIFEI versions and got the following output which SIFEI seems not to handle properly. No matter what causes this termination, the user should not be left without feedback in the UI.

See the attached log for details.

![screen](https://cloud.githubusercontent.com/assets/1338148/4977933/8ce3d5ca-68eb-11e4-942b-1d806e12d684.png)

**Comment by friederschueler** [comment]
I think we can close this issue.

**Comment by kuleszdl** [comment]
Yup, definitely. Thanks.
